'use client';

export type CardProposal={first:string;last:string;position:string;company:string;email:string;phone:string;mobile:string;website:string;address:string;city:string;country:string;linkedin:string;department:string;brand:string;needsReview:string[];provider:string};
export type VoiceProposal={summary:string;need:string;amount:string;volume:string;decision:string;objection:string;important:string;nextAction:string;nextActionDate:string;participants:string;place:string;stageName:string;provider:string};
const blankCard=():CardProposal=>({first:'',last:'',position:'',company:'',email:'',phone:'',mobile:'',website:'',address:'',city:'',country:'',linkedin:'',department:'',brand:'',needsReview:[],provider:'Saisie manuelle'});
const clean=(v:string)=>v.replace(/\s+/g,' ').trim();
function parseCardLines(raw:string[]):CardProposal{const p=blankCard(),lines=raw.map(clean).filter(Boolean);const email=lines.join(' ').match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i)?.[0]??'';const url=lines.join(' ').match(/(?:https?:\/\/)?(?:www\.)?[a-z0-9-]+(?:\.[a-z0-9-]+)+(?:\/[\w./?%&=-]*)?/i)?.[0]??'';const phones=lines.join(' ').match(/(?:\+?\d[\d .()/-]{7,}\d)/g)??[];p.email=email;p.website=url;p.phone=phones[0]??'';p.mobile=phones[1]??'';const skipped=new Set([email,url,...phones]);const content=lines.filter(x=>![...skipped].some(v=>v&&x.includes(v)));const nameLine=content.find(x=>/^[A-Za-zÀ-ÿ' -]{4,}$/.test(x)&&x.split(' ').length>=2);if(nameLine){const bits=nameLine.split(' ');p.first=bits.shift()??'';p.last=bits.join(' ')}const remaining=content.filter(x=>x!==nameLine);p.position=remaining.find(x=>/(direct|manager|responsable|commercial|sales|marketing|président|ceo|after|vente|atelier|owner)/i.test(x))??'';p.company=remaining.find(x=>x!==p.position&&(/[A-Z]{2,}/.test(x)||/motors|auto|group|cars|protech|concession/i.test(x)))??'';p.address=remaining.find(x=>/\d+.*(?:rue|avenue|road|street|boulevard|place)/i.test(x))??'';p.city=remaining.find(x=>/\b(?:monaco|nice|cannes|paris|duba[iy]|lyon|marseille)\b/i.test(x))??'';p.country=remaining.find(x=>/\b(?:france|monaco|uae|united arab emirates|italy|italie|egypt|égypte)\b/i.test(x))??'';if(!p.first||!p.last)p.needsReview.push('Nom');if(!p.company)p.needsReview.push('Entreprise');return p}
export interface BusinessCardExtractionService{extract(file:File):Promise<CardProposal>}
export class BrowserBusinessCardExtractionService implements BusinessCardExtractionService{async extract(file:File){const Detector=(window as unknown as {TextDetector?:new()=>{detect:(bitmap:ImageBitmap)=>Promise<{rawValue:string}[]>}}).TextDetector;if(!Detector)return {...blankCard(),provider:'OCR indisponible dans ce navigateur'};try{const bitmap=await createImageBitmap(file);const blocks=await new Detector().detect(bitmap);bitmap.close();return {...parseCardLines(blocks.map(b=>b.rawValue)),provider:'OCR du navigateur'}}catch{return {...blankCard(),provider:'Image non reconnue : saisie manuelle'}}}}
export interface TranscriptionService{start(onText:(text:string)=>void,onEnd:()=>void):{stop:()=>void;abort:()=>void}|null}
type Recognition={lang:string;continuous:boolean;interimResults:boolean;onresult:((event:{results:ArrayLike<ArrayLike<{transcript:string}>>})=>void)|null;onend:(()=>void)|null;start:()=>void;stop:()=>void;abort:()=>void};
export class BrowserTranscriptionService implements TranscriptionService{start(onText:(text:string)=>void,onEnd:()=>void){const Ctor=(window as unknown as {SpeechRecognition?:new()=>Recognition;webkitSpeechRecognition?:new()=>Recognition}).SpeechRecognition??(window as unknown as {webkitSpeechRecognition?:new()=>Recognition}).webkitSpeechRecognition;if(!Ctor)return null;const r=new Ctor();r.lang='fr-FR';r.continuous=true;r.interimResults=true;r.onresult=(e:{results:ArrayLike<ArrayLike<{transcript:string}>>})=>onText(Array.from(e.results).map(x=>x[0]?.transcript??'').join(' '));r.onend=onEnd;r.start();return {stop:()=>r.stop(),abort:()=>r.abort()}}}
const iso=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
export function resolveFrenchDate(text:string,base=new Date()):string{const t=text.toLocaleLowerCase();if(/demain/.test(t)){const d=new Date(base);d.setDate(d.getDate()+1);return iso(d)}if(/(?:jeudi prochain|jeudi)/.test(t)){const d=new Date(base);const delta=(4-d.getDay()+7)%7||7;d.setDate(d.getDate()+delta);return iso(d)}if(/la semaine prochaine/.test(t)){const d=new Date(base);d.setDate(d.getDate()+7);return iso(d)}if(/quinze jours/.test(t)){const d=new Date(base);d.setDate(d.getDate()+15);return iso(d)}return ''}
export interface StructuredExtractionService{extract(text:string):VoiceProposal}
export class RuleBasedStructuredExtractionService implements StructuredExtractionService{extract(text:string):VoiceProposal{const sentence=(re:RegExp)=>clean(text.match(re)?.[1]??'');const next=sentence(/(?:dois|veut|faut|à)\s+([^.!]+(?:mardi|jeudi|demain|semaine prochaine|quinze jours)?[^.!]*)/i);return {summary:clean(text),need:sentence(/intéress[ée]?\s+par\s+([^.!]+)/i),amount:sentence(/(?:montant|budget|devis)\s+(?:de\s+)?([\d .]+(?:€|eur)?)/i),volume:sentence(/([\d .]+\s+véhicules?\s+par\s+an)/i),decision:sentence(/(?:décision|valider|accord)\s*[:,-]?\s*([^.!]+)/i),objection:sentence(/(?:objection|bloqu|mais)\s*[:,-]?\s*([^.!]+)/i),important:'',nextAction:next,nextActionDate:resolveFrenchDate(text),participants:'',place:sentence(/(?:à|de)\s+(Nice|Cannes|Monaco|Dubaï|Paris)/i),stageName:/(négociation)/i.test(text)?'Négociation':'',provider:'Analyse locale assistée'}}}
