'use client';
import {useEffect,useMemo,useState} from 'react';
import {DataSyncPanel} from '@/components/data-sync-panel';
type Scope='OWN'|'TEAM'|'ALL';type User={id:string;name:string;email:string|null;roleId:string;teamIds:string[];teamNames:string[];active:number;scope:Scope;siteAccess:string;lastLoginAt:string|null;createdAt:string};type Team={id:string;name:string;active:number;managerUserId:string|null;userCount:number};type Permission={id:string;description:string};type State={capabilities:Record<string,boolean>;users:User[];teams:Team[];roles:{id:string;name:string}[];permissions:Permission[];rolePermissions:{roleId:string;permissionId:string;scope:Scope}[];rates:{id:string;baseCurrency:string;rate:number;effectiveDate:string;source:string}[];pipelines:{id:string;name:string;inactivityDays:number}[];audit:{id:string;timestamp:string;entityType:string;entityId:string;action:string;userName:string|null}[]};
const roleLabels:Record<string,string>={SUPERADMIN:'SuperAdmin',DIRECTION:'Direction',SALES_MANAGER:'Sales Manager',COMMERCIAL:'Commercial',CHARGE_AFFAIRES:"Chargé d’affaires",ADMIN_COMMERCIAL:'Administration commerciale',READ_ONLY:'Lecture seule'};const scopeLabels:Record<Scope,string>={OWN:'Mes données',TEAM:"Mes équipes",ALL:'Toutes les données'};
const roleDescriptions:Record<string,string>={SUPERADMIN:'Administration complète et accès global.',DIRECTION:'Pilotage global du CRM.',SALES_MANAGER:'Gestion et suivi de ses équipes.',COMMERCIAL:'Gestion de son portefeuille.',CHARGE_AFFAIRES:'Gestion de son portefeuille opérationnel et commercial.',ADMIN_COMMERCIAL:'Support administratif selon les droits.',READ_ONLY:'Consultation uniquement.'};
const siteAccessLabel=(value:string)=>({AUTHORIZED:'Autorisé',PENDING:'En attente',DENIED:'Non autorisé',UNKNOWN:'Inconnu'}[value]||'Inconnu');
const permissionFamilies=[
 {id:'account',label:'Comptes',description:'Fiches sociétés et rattachements'},
 {id:'contact',label:'Contacts',description:'Contacts professionnels et particuliers'},
 {id:'prospect',label:'Prospects',description:'Qualification et conversion'},
 {id:'opportunity',label:'Opportunités',description:'Pipeline, montants et décisions'},
 {id:'task',label:'Mon travail',description:'Tâches, relances et actions'},
 {id:'activity',label:'Activités',description:'Journal et comptes-rendus'},
 {id:'forecast',label:'Pilotage commercial',description:'Prévisions et lecture'},
 {id:'admin',label:'Administration',description:'Gestion de la configuration CRM'},
 {id:'audit',label:'Audit',description:'Historique des changements'},
 {id:'data',label:'Exports',description:'Extraction de données'},
];
const permissionLabels:Record<string,string>={read:'Consulter',create:'Créer',update:'Modifier',delete:'Supprimer',assign:'Réaffecter',convert:'Convertir',win:'Gagner',lose:'Perdre',complete:'Terminer',users:'Utilisateurs',roles:'Rôles et permissions',teams:'Équipes',rates:'Taux de change',config:'Configuration CRM',export:'Exporter'};
const permissionName=(permission:string)=>{const [,action]=permission.split('.');return permissionLabels[action]||action};
function UserForm({data,busy,save,user,onDone}:{data:State;busy:boolean;save:(value:Record<string,unknown>)=>Promise<void>;user?:User;onDone:()=>void}){
 const base=user??{name:'',email:'',roleId:'COMMERCIAL',teamIds:[] as string[],active:1,scope:'OWN' as Scope};
 const rank={OWN:0,TEAM:1,ALL:2};
 const effective=user?data.rolePermissions.filter(p=>p.roleId===user.roleId).map(p=>`${permissionName(p.permissionId)} · ${scopeLabels[rank[p.scope]<=rank[user.scope]?p.scope:user.scope]}`):[];
 return <form className="admin-new" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void save({kind:user?'user':'create-user',id:user?.id,name:f.get('name'),email:f.get('email'),roleId:f.get('roleId'),teamIds:f.getAll('teamIds').map(String),scope:f.get('scope'),active:f.get('active')==='on'}).then(onDone)}}>
  <input name="name" defaultValue={base.name} placeholder="Nom complet" required/>
  <input name="email" type="email" defaultValue={base.email||''} placeholder="email@entreprise.fr" required/>
  <select name="roleId" defaultValue={base.roleId}>{data.roles.map(r=><option value={r.id} key={r.id}>{roleLabels[r.id]||r.name}</option>)}</select>
  <fieldset className="admin-team-picker"><legend>Équipes</legend>{data.teams.map(team=><label key={team.id}><input name="teamIds" value={team.id} type="checkbox" defaultChecked={base.teamIds.includes(team.id)}/><span>{team.name}</span></label>)}</fieldset>
  <select name="scope" defaultValue={base.scope}>{(Object.keys(scopeLabels) as Scope[]).map(s=><option value={s} key={s}>{scopeLabels[s]}</option>)}</select>
  <label className="check"><input name="active" type="checkbox" defaultChecked={!!base.active}/> Actif</label>
  <button className="crm-primary" disabled={busy}>{user?'Enregistrer':'Créer l’utilisateur'}</button>
  <button type="button" onClick={onDone}>Annuler</button>
  {user?<details className="effective-permissions"><summary>Permissions effectives · {roleLabels[user.roleId]} / {scopeLabels[user.scope]}</summary><p>{roleDescriptions[user.roleId]}</p><div>{effective.map(item=><span key={item}>{item}</span>)}</div><small>Accès Site : {siteAccessLabel(user.siteAccess)} · Créé le {new Date(user.createdAt).toLocaleDateString('fr-FR')}</small></details>:<small>Utilisateur CRM créé. Les équipes peuvent être attribuées maintenant ou plus tard.</small>}
 </form>
}
export function AdminModule(){const [data,setData]=useState<State|null>(null),[tab,setTab]=useState('Utilisateurs'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[query,setQuery]=useState(''),[roleFilter,setRoleFilter]=useState(''),[teamFilter,setTeamFilter]=useState(''),[scopeFilter,setScopeFilter]=useState(''),[statusFilter,setStatusFilter]=useState(''),[selected,setSelected]=useState<User|null>(null),[newUser,setNewUser]=useState(false),[selectedRole,setSelectedRole]=useState('COMMERCIAL'),[permissionDraft,setPermissionDraft]=useState<Record<string,Scope|''>>({});
 const load=async()=>{const r=await fetch('/api/crm/admin',{cache:'no-store'}),b=await r.json() as State&{error?:string};if(!r.ok)throw new Error(b.error||'Chargement impossible.');setData(b)};useEffect(()=>{const timer=window.setTimeout(()=>{void load().catch(e=>setError(e.message))},0);return()=>window.clearTimeout(timer)},[]);
 const save=async(v:Record<string,unknown>)=>{setBusy(true);setError('');try{const r=await fetch('/api/crm/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(v)}),b=await r.json() as {error?:string};if(!r.ok)throw new Error(b.error||'Enregistrement impossible.');await load();setNewUser(false)}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const users=useMemo(()=>data?.users.filter(u=>`${u.name} ${u.email||''} ${u.roleId} ${u.teamNames.join(' ')}`.toLowerCase().includes(query.toLowerCase())&&(!roleFilter||u.roleId===roleFilter)&&(!teamFilter||u.teamIds.includes(teamFilter))&&(!scopeFilter||u.scope===scopeFilter)&&(!statusFilter||(statusFilter==='ACTIVE'?u.active===1:u.active===0)))??[],[data,query,roleFilter,teamFilter,scopeFilter,statusFilter]);const tabs=data?[['Utilisateurs','users'],['Équipes','teams'],['Rôles & permissions','roles'],['Taux de change','rates'],['Configuration CRM','config'],['Données','sync'],['Audit','audit']].filter(([,key])=>data.capabilities[key]):[];
 if(!data)return <div className="admin-panel">{error?<div className="crm-save-error">{error}</div>:<p>Chargement…</p>}</div>;
 return <><div className="page-intro"><div><div className="eyebrow">ESPACE COMMERCIAL <span>/</span> ADMINISTRATION</div><h1>Administration</h1><p>Gouvernance des accès, équipes, paramètres et audit.</p></div></div><nav className="tabs">{tabs.map(([label])=><button key={label} className={tab===label?'active':''} onClick={()=>setTab(label)}>{label}</button>)}</nav>{error&&<div className="crm-save-error" role="alert">{error}</div>}<div className="admin-panel">
 {tab==='Utilisateurs'&&<><div className="admin-actions"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher nom, e-mail, rôle ou équipe"/><select value={roleFilter} onChange={e=>setRoleFilter(e.target.value)}><option value="">Tous les rôles</option>{data.roles.map(r=><option key={r.id} value={r.id}>{roleLabels[r.id]}</option>)}</select><select value={teamFilter} onChange={e=>setTeamFilter(e.target.value)}><option value="">Toutes les équipes</option>{data.teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><select value={scopeFilter} onChange={e=>setScopeFilter(e.target.value)}><option value="">Tous les scopes</option>{(Object.keys(scopeLabels) as Scope[]).map(scope=><option key={scope} value={scope}>{scopeLabels[scope]}</option>)}</select><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="">Tous les statuts</option><option value="ACTIVE">Actif</option><option value="INACTIVE">Désactivé</option></select><button className="crm-primary" onClick={()=>{setSelected(null);setNewUser(true)}}>+ Nouvel utilisateur</button></div>{newUser&&<UserForm data={data} busy={busy} save={save} onDone={()=>setNewUser(false)}/>}<div className="user-table-scroll"><table className="user-matrix"><thead><tr><th>Utilisateur</th><th>Rôle</th><th>Équipes</th><th>Scope</th><th>Statut CRM</th><th>Accès Site</th><th>Dernière connexion</th><th>Actions</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><strong>{u.name}</strong><small>{u.email||'E-mail à renseigner'}</small></td><td><span className="user-role" title={roleDescriptions[u.roleId]}>{roleLabels[u.roleId]}</span></td><td>{u.teamNames.length?<div className="user-team-list">{u.teamNames.map(name=><span key={name}>{name}</span>)}</div>:<span className="user-no-team">Aucune équipe</span>}</td><td><span className="user-scope">{scopeLabels[u.scope]}</span></td><td><span className={u.active?'user-status active':'user-status inactive'}>{u.active?'Actif':'Désactivé'}</span></td><td><span className={u.siteAccess==='AUTHORIZED'?'site-status authorized':'site-status pending'}>{siteAccessLabel(u.siteAccess)}</span></td><td>{u.lastLoginAt?new Date(u.lastLoginAt).toLocaleString('fr-FR'):'Jamais'}</td><td><div className="user-actions"><button className="user-edit" onClick={()=>{setNewUser(false);setSelected(u)}}>Modifier</button><button className="user-secondary" disabled={busy} onClick={()=>void save({kind:'user',id:u.id,name:u.name,email:u.email||'',roleId:u.roleId,teamIds:u.teamIds,scope:u.scope,active:!u.active})}>{u.active?'Désactiver':'Réactiver'}</button><button className="user-secondary" onClick={()=>{setNewUser(false);setSelected(u)}}>Permissions</button></div></td></tr>)}</tbody></table></div>{selected&&<UserForm data={data} busy={busy} save={save} user={selected} onDone={()=>setSelected(null)}/>}</>}
 {tab==='Équipes'&&<><div className="team-table-scroll"><table className="team-matrix"><thead><tr><th>Équipe</th><th>Responsable</th><th>Utilisateurs</th><th>Statut</th><th>Action</th></tr></thead><tbody>{data.teams.map(t=><tr key={t.id}><td><input name="name" form={`team-${t.id}`} defaultValue={t.name} aria-label={`Nom de l’équipe ${t.name}`} required/></td><td><select name="manager" form={`team-${t.id}`} defaultValue={t.managerUserId||''} aria-label={`Responsable de ${t.name}`}><option value="">Sans responsable</option>{data.users.filter(u=>u.active).map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></td><td><span className="team-count">{t.userCount}</span></td><td><select className={t.active?'team-status active':'team-status inactive'} name="active" form={`team-${t.id}`} defaultValue={t.active?'true':'false'} aria-label={`Statut de ${t.name}`}><option value="true">Active</option><option value="false">Désactivée</option></select></td><td><form id={`team-${t.id}`} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void save({kind:'team',id:t.id,name:f.get('name'),managerUserId:f.get('manager'),active:f.get('active')==='true'})}}><button className="team-save" disabled={busy}>Enregistrer</button></form></td></tr>)}</tbody></table></div><form className="admin-new team-create" onSubmit={e=>{e.preventDefault();void save({kind:'team',name:new FormData(e.currentTarget).get('name'),active:true})}}><strong>Nouvelle équipe</strong><input name="name" placeholder="Nom de l’équipe" required/><button className="crm-primary">Créer l’équipe</button></form></>}
 {tab==='Rôles & permissions'&&<><div className="permission-intro"><div><strong>Choisir un rôle</strong><select value={selectedRole} onChange={e=>{setSelectedRole(e.target.value);setPermissionDraft({})}}>{data.roles.map(r=><option key={r.id} value={r.id}>{roleLabels[r.id]}</option>)}</select></div><p>Choisissez un niveau pour une famille complète, puis affinez chaque droit si nécessaire. Le périmètre défini sur l’utilisateur reste toujours prioritaire.</p></div>{selectedRole==='SUPERADMIN'?<p>Les droits SuperAdmin sont système et non modifiables.</p>:<form onSubmit={e=>{e.preventDefault();const permissions=data.permissions.flatMap(p=>{const current=data.rolePermissions.find(x=>x.roleId===selectedRole&&x.permissionId===p.id)?.scope||'';const scope=permissionDraft[p.id]??current;return scope?[{permissionId:p.id,scope}]:[]});void save({kind:'role-permissions',roleId:selectedRole,permissions})}}><div className="permission-table-scroll"><table className="permission-matrix"><thead><tr><th>Droit</th><th>Aucun</th><th>Mes données</th><th>Mon équipe</th><th>Toutes les données</th></tr></thead><tbody>{permissionFamilies.map(family=>{const entries=data.permissions.filter(p=>p.id.split('.')[0]===family.id);if(!entries.length)return null;const currentScope=(p:Permission)=>permissionDraft[p.id]??(data.rolePermissions.find(x=>x.roleId===selectedRole&&x.permissionId===p.id)?.scope||'');const familyScope=entries.every(p=>currentScope(p)===currentScope(entries[0]))?currentScope(entries[0]):'MIXED';return <><tr className="permission-family" key={`${family.id}-family`}><th colSpan={2}><strong>{family.label}</strong><small>{family.description}</small></th><td colSpan={3}><label>Appliquer à toute la famille<select aria-label={`Droits ${family.label}`} value={familyScope} onChange={e=>{if(e.target.value!=='MIXED')setPermissionDraft(previous=>Object.fromEntries([...Object.entries(previous),...entries.map(p=>[p.id,e.target.value as Scope|''])]))}}><option value="MIXED" disabled>Choisir…</option><option value="">Aucun accès</option><option value="OWN">Mes données</option><option value="TEAM">Mon équipe</option><option value="ALL">Toutes les données</option></select></label></td></tr>{entries.map(p=>{const scope=currentScope(p);return <tr key={p.id}><th scope="row">{permissionName(p.id)}<small>{p.id}</small></th>{(['','OWN','TEAM','ALL'] as const).map(value=><td key={value}><button type="button" className={scope===value?'selected':''} aria-pressed={scope===value} onClick={()=>setPermissionDraft(previous=>({...previous,[p.id]:value}))}>{value?scopeLabels[value]:'—'}</button></td>)}</tr>})}</>})}</tbody></table></div><div className="permission-actions"><span>Les modifications sont appliquées uniquement après validation.</span><button className="crm-primary" disabled={busy}>Enregistrer les droits</button></div></form>}</>}
 {tab==='Taux de change'&&<><form className="admin-new rate-create" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void save({kind:'rate',baseCurrency:f.get('currency'),rate:Number(f.get('rate')),effectiveDate:f.get('date')})}}><strong>Nouveau taux</strong><select name="currency">{['USD','GBP','AED','EUR'].map(c=><option key={c}>{c}</option>)}</select><span>→ EUR</span><input name="rate" type="number" min="0.000001" step="any" placeholder="Taux" required/><input name="date" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/><button className="crm-primary">Enregistrer</button></form><div className="admin-data-scroll"><table className="admin-data-table"><thead><tr><th>Devise</th><th>Conversion</th><th>Taux</th><th>Date d’effet</th><th>Source</th></tr></thead><tbody>{data.rates.map(r=><tr key={r.id}><td><strong>{r.baseCurrency}</strong></td><td>{r.baseCurrency} → EUR</td><td><strong>{r.rate}</strong></td><td>{r.effectiveDate}</td><td><span className="data-badge">{r.source}</span></td></tr>)}</tbody></table></div></>}
 {tab==='Configuration CRM'&&<div className="admin-data-scroll"><table className="admin-data-table config-table"><thead><tr><th>Pipeline</th><th>Seuil d’inactivité</th><th>Action</th></tr></thead><tbody>{data.pipelines.map(p=><tr key={p.id}><td><strong>{p.name}</strong></td><td><form id={`pipeline-${p.id}`} onSubmit={e=>{e.preventDefault();void save({kind:'pipeline',id:p.id,inactivityDays:Number(new FormData(e.currentTarget).get('days'))})}}><label><input name="days" type="number" min="1" max="365" defaultValue={p.inactivityDays}/><span>jours</span></label></form></td><td><button className="table-save" form={`pipeline-${p.id}`}>Enregistrer</button></td></tr>)}</tbody></table></div>}
 {tab==='Données'&&<DataSyncPanel/>}
 {tab==='Audit'&&<div className="admin-data-scroll"><table className="admin-data-table audit-table"><thead><tr><th>Date et heure</th><th>Action</th><th>Objet</th><th>Acteur</th></tr></thead><tbody>{data.audit.map(x=><tr key={x.id}><td>{new Date(x.timestamp).toLocaleString('fr-FR')}</td><td><strong>{x.action}</strong></td><td>{x.entityType} <small>{x.entityId}</small></td><td>{x.userName||'Système'}</td></tr>)}</tbody></table></div>}</div></>}
