'use client';
import {useState} from 'react';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {contactInterests} from '@/types/crm';
import type {Contact,Opportunity,ServiceCenter} from '@/types/crm';
import {mockPipelines,openStages} from '@/data/pipelines';
import {todayLocal,taskForNextAction} from '@/data/work';
import {localId} from '@/utils/local-id';
import type {Task} from '@/types/crm';

type Props={contact:Contact|null;centers:ServiceCenter[];onClose:()=>void;onCreate:(o:Opportunity)=>void;onTask:(t:Task)=>void};
export function B2COpportunityCreate({contact,centers,onClose,onCreate,onTask}:Props){
 const [name,setName]=useState(''),[service,setService]=useState(''),[amount,setAmount]=useState(''),[next,setNext]=useState(''),[due,setDue]=useState(''),[stageId,setStageId]=useState(''),[center,setCenter]=useState(''),[make,setMake]=useState(''),[model,setModel]=useState(''),[year,setYear]=useState(''),[registration,setRegistration]=useState(''),[vin,setVin]=useState('');
 if(!contact)return null;
 const pipeline=mockPipelines.find(p=>p.id==='services')!,stage=openStages('services')[0];
 function submit(e:React.FormEvent){e.preventDefault();if(!contact||!name.trim()||!next.trim()||!due)return;const amountValue=amount.trim()?Number(amount):0;if(!Number.isFinite(amountValue)||amountValue<0)return;const now=todayLocal(),chosen=pipeline.stages.find(s=>s.id===stageId)??stage;
  const o:Opportunity={id:localId(),name:name.trim(),customerType:'B2C',accountId:null,primaryContactId:contact.id,siteId:null,centerId:center||contact.originCenterId||null,serviceType:service||undefined,vehicleMake:make||undefined,vehicleModel:model||undefined,vehicleYear:year||undefined,vehicleRegistration:registration||undefined,vehicleVin:vin||undefined,businessLine:'Services',pipelineId:'services',stageId:chosen.id,ownerId:contact.ownerId,status:'Open',amount:amountValue,currency:'EUR',probability:chosen.probability,weightedAmount:amountValue*chosen.probability/100,expectedCloseDate:'',priority:'Normale',source:contact.source??'Contact particulier',description:'',nextAction:next.trim(),nextActionDate:due,lastActivityDate:now,createdAt:now,updatedAt:now,stageEnteredAt:now};
  onCreate(o);onTask(taskForNextAction({contactId:contact.id,opportunityId:o.id},next.trim(),due,contact.ownerId));onClose();
 }
 return <Dialog open onOpenChange={v=>{if(!v)onClose()}}><DialogContent className="crm-dialog b2c-dialog"><DialogHeader><DialogTitle>Opportunité · {contact.first} {contact.last}</DialogTitle><DialogDescription>Une demande commerciale qualifiée, liée à ce contact particulier sans créer de compte.</DialogDescription></DialogHeader><form className="crm-form" onSubmit={submit}><label>Nom de l’opportunité<input required value={name} onChange={e=>setName(e.target.value)} placeholder="PPF · véhicule de Jean Dupont"/></label><div className="crm-form-pair"><label>Prestation<select value={service} onChange={e=>setService(e.target.value)}><option value="">À préciser</option>{contactInterests.map(i=><option key={i}>{i}</option>)}</select></label><label>Montant potentiel (€), facultatif<input type="number" min="0" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="À qualifier"/></label></div><div className="crm-form-pair"><label>Étape<select value={stageId||stage.id} onChange={e=>setStageId(e.target.value)}>{pipeline.stages.filter(s=>!s.terminal).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Centre concerné<select value={center||contact.originCenterId||''} onChange={e=>setCenter(e.target.value)}><option value="">Non précisé</option>{centers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></div><div className="crm-form-pair"><label>Prochaine action<input required value={next} onChange={e=>setNext(e.target.value)} placeholder="Envoyer le devis"/></label><label>Date<input type="date" required value={due} onChange={e=>setDue(e.target.value)} onInput={e=>setDue(e.currentTarget.value)}/></label></div><details><summary>Véhicule (facultatif)</summary><div className="crm-form-pair"><label>Marque<input value={make} onChange={e=>setMake(e.target.value)}/></label><label>Modèle<input value={model} onChange={e=>setModel(e.target.value)}/></label></div><div className="crm-form-pair"><label>Année<input value={year} onChange={e=>setYear(e.target.value)}/></label><label>Immatriculation<input value={registration} onChange={e=>setRegistration(e.target.value)}/></label></div><label>VIN<input value={vin} onChange={e=>setVin(e.target.value)}/></label></details><button className="crm-primary">Créer l’opportunité</button></form></DialogContent></Dialog>;
}
