'use client';
import {useState} from 'react';
import {CalendarDays,Mail,MessageSquareText,NotebookPen,Phone,Plus} from 'lucide-react';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {QuickTaskForm} from '@/components/work-forms';
import {openCapture} from '@/components/capture-assistant';
import {activityMatches,createActivity,currentUserId,linkFor,todayLocal} from '@/data/work';
import type {Account,AccountStatus,Activity,BusinessLine,Contact,CrmLinks,Task} from '@/types/crm';
import {mockUsers} from '@/data/crm';
const icons={Note:NotebookPen,Appel:Phone,Email:Mail,Meeting:CalendarDays,Visite:CalendarDays,Démonstration:CalendarDays,Salon:MessageSquareText,'Compte-rendu':NotebookPen,Autre:MessageSquareText};
export const nameOf=(id:string)=>mockUsers.find(u=>u.id===id)?.name??'À attribuer';
export function BusinessChips({lines}:{lines:BusinessLine[]}){return <span className="business-chips">{lines.map(l=><span key={l} className={`line-tag line-${l.toLowerCase().replaceAll(' ','-')}`}>{l}</span>)}</span>}
export function AccountStatusCell({status,onChange}:{status:AccountStatus;onChange?:(v:AccountStatus)=>void}){const statuses=['Prospect','Client actif','Partenaire','Dormant','Ancien client','À qualifier'] as AccountStatus[];return onChange?<select className={`account-status as-${status.toLowerCase().replaceAll(' ','-')}`} aria-label="Statut du compte" value={status} onChange={e=>onChange(e.target.value as AccountStatus)}>{statuses.map(s=><option key={s}>{s}</option>)}</select>:<span className={`account-status as-${status.toLowerCase().replaceAll(' ','-')}`}>{status}</span>}
export function ActivityItem({activity,context,onOpen}:{activity:Activity;context?:string;onOpen?:()=>void}){const Icon=icons[activity.type];return <li><span className="activity-icon"><Icon size={15}/></span><div><div className="activity-heading"><strong>{activity.title}</strong><small>{new Intl.DateTimeFormat('fr-FR',{day:'numeric',month:'short',year:'numeric'}).format(new Date(`${activity.activityDate}T12:00:00`))}{activity.activityTime?` · ${activity.activityTime}`:''}</small></div><p>{activity.content}</p>{activity.outcome&&<small>Résultat : {activity.outcome}</small>}{activity.participants&&<small>Participants : {activity.participants}</small>}{context&&<small>{context}</small>}<small>{nameOf(activity.userId)} · {activity.type}</small>{onOpen&&<button type="button" className="crm-link" onClick={onOpen}>Ouvrir la fiche liée</button>}</div></li>}
export function ActivityTimeline({activities,subjectType,subjectId,onAdd,scope,contextFor}:{activities:Activity[];subjectType:'prospect'|'account'|'contact'|'opportunity';subjectId:string;onAdd:(a:Activity)=>void;scope?:CrmLinks[];contextFor?:(a:Activity)=>string}){const [text,setText]=useState('');const links=scope??[linkFor(subjectType,subjectId)];const rows=activities.filter(a=>links.some(link=>activityMatches(a,link))).sort((a,b)=>b.activityDate.localeCompare(a.activityDate)||b.createdAt.localeCompare(a.createdAt));function submit(e:React.FormEvent){e.preventDefault();if(!text.trim())return;onAdd(createActivity({...linkFor(subjectType,subjectId),type:'Note',title:'Note',content:text.trim(),activityDate:todayLocal(),userId:currentUserId}));setText('')}return <div className="shared-history"><div className="detail-section-title"><h3>Historique commercial</h3><span className="history-count">{rows.length}</span></div>{rows.length?<ol className="activity-list">{rows.map(a=><ActivityItem key={a.id} activity={a} context={contextFor?.(a)}/>)}</ol>:<p className="no-activity">Aucune activité enregistrée.</p>}<button type="button" className="voice-note-link" onClick={()=>openCapture({mode:'voice',links:linkFor(subjectType,subjectId)})}>Dicter une note assistée</button><form className="note-form" onSubmit={submit}><label htmlFor={`note-${subjectType}-${subjectId}`}>Ajouter une note</label><textarea id={`note-${subjectType}-${subjectId}`} rows={3} value={text} onChange={e=>setText(e.target.value)} placeholder="Résumez un échange ou une information utile…"/><button type="submit" disabled={!text.trim()}><Plus size={15}/>Ajouter la note</button></form></div>}
export function TaskComposer({open,onClose,subjectType,subjectId,onAdd,ownerId,accountId}:{open:boolean;onClose:()=>void;subjectType:'prospect'|'account'|'contact'|'opportunity';subjectId:string;onAdd:(t:Task)=>void;ownerId?:string;accountId?:string}){return <QuickTaskForm open={open} onClose={onClose} onAdd={onAdd} links={{...linkFor(subjectType,subjectId),accountId:subjectType==='account'?subjectId:accountId}} defaultOwnerId={ownerId??currentUserId}/>}
export function DuplicatePrompt({open,title,candidate,details,onView,onAnyway,onCancel,viewLabel="Voir le compte"}:{open:boolean;title:string;candidate:string;details:string;onView:()=>void;onAnyway:()=>void;onCancel:()=>void;viewLabel?:string}){return <Dialog open={open} onOpenChange={v=>{if(!v)onCancel()}}><DialogContent className="crm-dialog"><DialogHeader><DialogTitle>{title}</DialogTitle><DialogDescription>Vérifiez la fiche existante avant de poursuivre.</DialogDescription></DialogHeader><div className="duplicate-candidate"><strong>{candidate}</strong><span>{details}</span></div><div className="duplicate-actions"><button onClick={onCancel}>Annuler</button><button onClick={onAnyway}>Créer quand même</button><button className="crm-primary" onClick={onView}>{viewLabel}</button></div></DialogContent></Dialog>}
export function AccountCard({a,contacts,sites,onOpen}:{a:Account;contacts:Contact[];sites:number;onOpen:()=>void}){return <button className="crm-mobile-card" onClick={onOpen}><div className="crm-card-top"><strong>{a.name}</strong><span>{a.type}</span></div><div className="crm-card-row"><AccountStatusCell status={a.status}/><span>{a.city}, {a.country}</span></div><BusinessChips lines={a.lines}/><div className="crm-card-meta"><span>Owner : {nameOf(a.ownerId)}</span><span>{contacts.length} contacts · {sites} sites</span></div><div className="crm-card-action"><span>{a.nextAction}</span><strong>{a.nextDate}</strong></div></button>}
