'use client';
import {useEffect,useState} from 'react';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {activityTypes,callOutcomes,taskPriorities,taskTypes} from '@/types/crm';
import type {Account,Activity,ActivityType,Contact,CrmLinks,Opportunity,Task,TaskPriority,TaskType} from '@/types/crm';
import type {Prospect} from '@/types/prospect';
import {mockUsers} from '@/data/crm';
import {createActivity,createTask,currentUserId,taskForNextAction,todayLocal} from '@/data/work';
export type WorkRefs={prospects?:Prospect[];accounts?:Account[];contacts?:Contact[];opportunities?:Opportunity[]};
function targetOptions({prospects=[],accounts=[],contacts=[],opportunities=[]}:WorkRefs){return [...prospects.map(p=>({value:`prospect:${p.id}`,label:`Prospect · ${p.first} ${p.last}`})),...accounts.map(a=>({value:`account:${a.id}`,label:`Compte · ${a.name}`})),...contacts.map(c=>({value:`contact:${c.id}`,label:`Contact · ${c.first} ${c.last}`})),...opportunities.map(o=>({value:`opportunity:${o.id}`,label:`Opportunité · ${o.name}`}))]}
function linksFor(value:string,refs:WorkRefs):CrmLinks{const [type,id]=value.split(':');if(type==='opportunity'){const o=refs.opportunities?.find(x=>x.id===id);return {opportunityId:id,accountId:o?.accountId??undefined,contactId:o?.primaryContactId??undefined}}if(type==='contact'){const c=refs.contacts?.find(x=>x.id===id);return {contactId:id,accountId:c?.accountId??undefined}}if(type==='account')return {accountId:id};if(type==='prospect')return {prospectId:id};return {}}
 // Reused task dialog resets defaults on opening.
 // eslint-disable-next-line react-hooks/set-state-in-effect
export function QuickTaskForm({open,onClose,onAdd,links={},defaultOwnerId=currentUserId,refs={},defaultTitle='',defaultDate='',sourceNextAction=false}:{open:boolean;onClose:()=>void;onAdd:(t:Task)=>void;links?:CrmLinks;defaultOwnerId?:string;refs?:WorkRefs;defaultTitle?:string;defaultDate?:string;sourceNextAction?:boolean}){const [title,setTitle]=useState(defaultTitle);const [description,setDescription]=useState('');const [owner,setOwner]=useState(defaultOwnerId);const [date,setDate]=useState(defaultDate||todayLocal());const [time,setTime]=useState('');const [type,setType]=useState<TaskType>('Relance');const [priority,setPriority]=useState<TaskPriority>('Normale');const [target,setTarget]=useState('');useEffect(()=>{if(open){setTitle(defaultTitle);setOwner(defaultOwnerId);setDate(defaultDate||todayLocal());setTarget('')}},[open,defaultTitle,defaultOwnerId,defaultDate]);const fixed=Object.values(links).some(Boolean);return <Dialog open={open} onOpenChange={v=>{if(!v)onClose()}}><DialogContent className="crm-dialog work-dialog"><DialogHeader><DialogTitle>Nouvelle tâche</DialogTitle><DialogDescription>Une action courte, avec un responsable et une échéance.</DialogDescription></DialogHeader><form className="crm-form" onSubmit={e=>{e.preventDefault();const selected=fixed?links:linksFor(target,refs);onAdd(createTask({...selected,title:title.trim(),description:description.trim(),ownerId:owner,dueDate:date,dueTime:time||undefined,priority,taskType:type,sourceNextAction}));setTitle('');setDescription('');onClose()}}><label>Type<select value={type} onChange={e=>setType(e.target.value as TaskType)}>{taskTypes.map(t=><option key={t}>{t}</option>)}</select></label><label>Titre<input required value={title} onChange={e=>setTitle(e.target.value)} placeholder="Ex. Relancer la proposition"/></label><div className="crm-form-pair"><label>Responsable<select value={owner} onChange={e=>setOwner(e.target.value)}>{mockUsers.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label><label>Priorité<select value={priority} onChange={e=>setPriority(e.target.value as TaskPriority)}>{taskPriorities.map(p=><option key={p}>{p}</option>)}</select></label></div><div className="crm-form-pair"><label>Date<input required type="date" value={date} onChange={e=>setDate(e.target.value)} onInput={e=>setDate(e.currentTarget.value)}/></label><label>Heure facultative<input type="time" value={time} onChange={e=>setTime(e.target.value)} onInput={e=>setTime(e.currentTarget.value)}/></label></div>{!fixed&&<label>Objet lié<select value={target} onChange={e=>setTarget(e.target.value)}><option value="">Aucun</option>{targetOptions(refs).map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label>}<label>Notes<textarea value={description} onChange={e=>setDescription(e.target.value)}/></label><button className="crm-primary">Créer la tâche</button></form></DialogContent></Dialog>}
 // Reused activity dialog resets defaults on opening.
 // eslint-disable-next-line react-hooks/set-state-in-effect
export function QuickActivityForm({open,onClose,onAdd,onTask,links={},refs={},defaultType='Note',defaultTitle='',defaultUserId=currentUserId}:{open:boolean;onClose:()=>void;onAdd:(a:Activity)=>void;onTask?:(t:Task)=>void;links?:CrmLinks;refs?:WorkRefs;defaultType?:ActivityType;defaultTitle?:string;defaultUserId?:string}){const [type,setType]=useState<ActivityType>(defaultType);const [title,setTitle]=useState(defaultTitle);const [content,setContent]=useState('');const [date,setDate]=useState(todayLocal());const [time,setTime]=useState('');const [participants,setParticipants]=useState('');const [outcome,setOutcome]=useState('');const [next,setNext]=useState('');const [nextDate,setNextDate]=useState('');const [addTask,setAddTask]=useState(true);const [target,setTarget]=useState('');useEffect(()=>{if(open){setType(defaultType);setTitle(defaultTitle);setContent('');setDate(todayLocal());setNext('');setNextDate('');setTarget('')}},[open,defaultType,defaultTitle]);const fixed=Object.values(links).some(Boolean);function submit(e:React.FormEvent){e.preventDefault();const selected=fixed?links:linksFor(target,refs);const createdTask=!!(next.trim()&&nextDate&&addTask&&onTask);onAdd(createActivity({...selected,type,title:title.trim()||type,content:content.trim(),userId:defaultUserId,activityDate:date,activityTime:time||undefined,participants:type==='Meeting'?participants:undefined,outcome:type==='Appel'?outcome:undefined,nextActionCreated:createdTask}));if(createdTask)onTask!(taskForNextAction(selected,next.trim(),nextDate,defaultUserId));onClose()}
 return <Dialog open={open} onOpenChange={v=>{if(!v)onClose()}}><DialogContent className="crm-dialog work-dialog"><DialogHeader><DialogTitle>{type==='Appel'?'Compte-rendu d’appel':type==='Meeting'?'Enregistrer un meeting':'Nouvelle activité'}</DialogTitle><DialogDescription>Consignez cet échange sur la fiche concernée.</DialogDescription></DialogHeader><form className="crm-form" onSubmit={submit}><label>Type<select value={type} onChange={e=>setType(e.target.value as ActivityType)}>{activityTypes.map(t=><option key={t}>{t}</option>)}</select></label><label>Titre<input value={title} onChange={e=>setTitle(e.target.value)} placeholder={type==='Appel'?'Appel de suivi':'Résumé de l’activité'}/></label><div className="crm-form-pair"><label>Date<input type="date" required value={date} onChange={e=>setDate(e.target.value)} onInput={e=>setDate(e.currentTarget.value)}/></label><label>Heure<input type="time" value={time} onChange={e=>setTime(e.target.value)} onInput={e=>setTime(e.currentTarget.value)}/></label></div>{type==='Appel'&&<label>Résultat<select required value={outcome} onChange={e=>setOutcome(e.target.value)}><option value="">Choisir</option>{callOutcomes.map(o=><option key={o}>{o}</option>)}</select></label>}{type==='Meeting'&&<label>Participants<input value={participants} onChange={e=>setParticipants(e.target.value)} placeholder="Noms des participants"/></label>}<label>{type==='Meeting'?'Compte-rendu':'Note'}<textarea required value={content} onChange={e=>setContent(e.target.value)}/></label>{!fixed&&<label>Fiche liée<select required value={target} onChange={e=>setTarget(e.target.value)}><option value="">Choisir une fiche</option>{targetOptions(refs).map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label>}<div className="crm-form-pair"><label>Prochaine action<input value={next} onChange={e=>setNext(e.target.value)}/></label><label>Date de relance<input type="date" value={nextDate} onChange={e=>setNextDate(e.target.value)} onInput={e=>setNextDate(e.currentTarget.value)}/></label></div>{next&&nextDate&&<label className="check-option"><input type="checkbox" checked={addTask} onChange={e=>setAddTask(e.target.checked)}/>Ajouter à Mon travail</label>}<button className="crm-primary">Enregistrer l’activité</button></form></DialogContent></Dialog>}
