import type {Actor} from './auth';
import {AccessError,allowed,requirePermission} from './auth';
import {rateFor} from './admin';
import {normalizeDomain,normalizeEmail,normalizeName,normalizePhone,normalizeTaxId} from './normalize';
import {contactInterests,contactSources,relationshipStatuses} from '@/types/crm';

type DB=Actor['db'];
// Stored CRM payloads have different legacy shapes per entity; the repository validates each shape before writing.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type LegacyPayload=Record<string,any>;
export const entities={accounts:{table:'accounts',singular:'account',owner:'owner_id'},sites:{table:'account_sites',singular:'account',owner:'owner_id'},contacts:{table:'contacts',singular:'contact',owner:'owner_id'},prospects:{table:'prospects',singular:'prospect',owner:'owner_id'},opportunities:{table:'opportunities',singular:'opportunity',owner:'owner_id'},tasks:{table:'tasks',singular:'task',owner:'owner_id'},activities:{table:'activities',singular:'activity',owner:'user_id'}} as const;
export type Entity=keyof typeof entities;
const now=()=>new Date().toISOString();
const uuid=()=>crypto.randomUUID();
const owner=(entity:Entity,v:LegacyPayload)=>entity==='activities'?v.userId:v.ownerId;
const idOf=(v:LegacyPayload)=>String(v.id);
const linkedPermissions=[['prospectId','prospects','prospect.read'],['accountId','accounts','account.read'],['contactId','contacts','contact.read'],['opportunityId','opportunities','opportunity.read']] as const;
async function linkedVisible(a:Actor,value:Record<string,unknown>,cache:Map<string,boolean>){for(const [key,table,permission] of linkedPermissions){if(!value[key])continue;const cacheKey=`${table}:${String(value[key])}`;let canRead=cache.get(cacheKey);if(canRead===undefined){const row=await a.db.prepare(`SELECT owner_id AS ownerId FROM ${table} WHERE id=? AND deleted_at IS NULL`).bind(String(value[key])).first<{ownerId:string}>();canRead=!!row&&await allowed(a,permission,row.ownerId);cache.set(cacheKey,canRead)}if(!canRead){if(key==='accountId'&&value.opportunityId){const linked=await a.db.prepare('SELECT account_id AS accountId,owner_id AS ownerId FROM opportunities WHERE id=? AND deleted_at IS NULL').bind(String(value.opportunityId)).first<{accountId:string;ownerId:string}>();if(linked&&linked.accountId===value.accountId&&await allowed(a,'opportunity.read',linked.ownerId))continue}return false}}return true}
export async function rows(a:Actor,entity:Entity){const cfg=entities[entity],permission=`${cfg.singular}.read`;await requirePermission(a,permission);const data=await a.db.prepare(`SELECT payload,${cfg.owner} AS ownerId FROM ${cfg.table} WHERE deleted_at IS NULL`).all<{payload:string;ownerId:string}>();const visible=[];const linkedCache=new Map<string,boolean>();for(const r of data.results){if(!await allowed(a,permission,r.ownerId))continue;const value=JSON.parse(r.payload);if((entity==='activities'||entity==='tasks')&&!await linkedVisible(a,value,linkedCache))continue;if((entity==='sites'||entity==='contacts')&&value.accountId&&!await linkedVisible(a,{accountId:value.accountId},linkedCache))continue;if(entity==='contacts'){value.contactType??='BUSINESS';value.relationshipStatus??=value.status==='Actif'?'Client actif':value.status==='Inactif'?'Inactif':'Prospect';value.interests??=[]}if(entity==='opportunities')value.customerType??='B2B';visible.push(value)}return visible}
export async function snapshot(a:Actor){const history=await a.db.prepare('SELECT task_id AS taskId,user_id AS userId,old_date AS oldDate,new_date AS newDate,timestamp,reason FROM task_history ORDER BY timestamp DESC LIMIT 200').all<{taskId:string;userId:string;oldDate:string;newDate:string;timestamp:string;reason:string|null}>();const config=await a.db.prepare('SELECT id,inactivity_days AS days FROM pipelines').all<{id:string;days:number}>();const centers=await a.db.prepare('SELECT id,name,active FROM service_centers WHERE active=1 ORDER BY name').all<{id:string;name:string;active:number}>();const [accounts,sites,contacts,prospects,opportunities,tasks,activities]=await Promise.all((Object.keys(entities) as Entity[]).map(e=>rows(a,e)));return {taskHistory:history.results.filter(h=>tasks.some((t:{id?:string})=>t.id===h.taskId)),inactivityDays:Object.fromEntries(config.results.map(x=>[x.id,x.days])),serviceCenters:centers.results.map(c=>({...c,active:!!c.active})),actor:{id:a.id,name:a.name,roleId:a.roleId,teamId:a.teamId,permissions:a.permissions},accounts,sites,contacts,prospects,opportunities,tasks,activities}}
export async function findRow(a:Actor,entity:Entity,id:string){const cfg=entities[entity];return a.db.prepare(`SELECT payload,${cfg.owner} AS ownerId FROM ${cfg.table} WHERE id=? AND deleted_at IS NULL`).bind(id).first<{payload:string;ownerId:string}>()}
const scalar=(entity:Entity,v:LegacyPayload)=>{
 const common=entity==='activities'?{user_id:v.userId,payload:JSON.stringify(v),updated_at:now()}:{owner_id:owner(entity,v),payload:JSON.stringify(v),updated_at:now()};
 switch(entity){case 'accounts':return {...common,parent_id:v.parentId??null,name:v.name,normalized_name:normalizeName(v.name??''),domain:normalizeDomain(v.website??''),tax_id_normalized:normalizeTaxId(v.taxId??''),phone_normalized:normalizePhone(v.phone??'')};
 case 'sites':return {...common,account_id:v.accountId};
 case 'contacts':return {...common,account_id:v.accountId??null,site_id:v.siteId??null,contact_type:v.contactType??'BUSINESS',relationship_status:v.relationshipStatus??'Prospect',source:v.source??null,origin_center_id:v.originCenterId??null,email_normalized:normalizeEmail(v.email??''),phone_normalized:normalizePhone(v.phone||v.mobile||''),name_normalized:normalizeName(`${v.first??''} ${v.last??''}`)};
 case 'prospects':return {...common,account_id:v.accountId??null,contact_id:v.contactId??null,opportunity_id:v.opportunityId??null,next_action_date:v.nextActionDate??null,converted_by:v.convertedBy??null};
 case 'opportunities':return {...common,account_id:v.accountId??null,site_id:v.siteId??null,primary_contact_id:v.primaryContactId??null,customer_type:v.customerType??'B2B',center_id:v.centerId??null,pipeline_id:v.pipelineId,stage_id:v.stageId,status:v.status,native_amount:v.nativeAmount??v.amount,currency:v.currency,next_action_date:v.nextActionDate??null,exchange_rate_snapshot:v.exchangeRateSnapshot??null,exchange_rate_date:v.exchangeRateDate??null,amount_eur:v.amountEUR??null};
 case 'activities':return {...common,prospect_id:v.prospectId??null,account_id:v.accountId??null,contact_id:v.contactId??null,opportunity_id:v.opportunityId??null,activity_date:v.activityDate};
 case 'tasks':return {...common,prospect_id:v.prospectId??null,account_id:v.accountId??null,contact_id:v.contactId??null,opportunity_id:v.opportunityId??null,activity_id:v.activityId??null,due_date:v.dueDate,status:v.status};
 }};
async function exists(db:DB,table:string,id:string|null|undefined){if(!id)return false;return !!await db.prepare(`SELECT id FROM ${table} WHERE id=? AND deleted_at IS NULL`).bind(String(id)).first()}
async function validate(a:Actor,entity:Entity,v:LegacyPayload,creating:boolean,previous?:LegacyPayload|null){
 const db=a.db;if(!v.id||!owner(entity,v))throw new AccessError('INVALID','Identifiant et responsable requis.');
 if(!await exists(db,'users',owner(entity,v)))throw new AccessError('INVALID','Responsable inconnu.');
 if(entity==='accounts'&&(!v.name?.trim()||v.parentId&&(!await exists(db,'accounts',v.parentId)||v.parentId===v.id)))throw new AccessError('INVALID','Compte ou hiérarchie invalide.');
 if(entity==='sites'&&!await exists(db,'accounts',v.accountId))throw new AccessError('INVALID','Compte lié requis.');
 if(entity==='contacts'){
  const type=v.contactType??'BUSINESS';
  if(!['BUSINESS','INDIVIDUAL'].includes(type)||!v.last?.trim()||type==='BUSINESS'&&!await exists(db,'accounts',v.accountId))throw new AccessError('INVALID','Type, nom ou compte professionnel invalide.');
  if(v.accountId&&!await exists(db,'accounts',v.accountId))throw new AccessError('INVALID','Compte lié introuvable.');
  if(type==='INDIVIDUAL'&&v.accountId)throw new AccessError('INVALID','Un particulier ne possède pas de compte.');
  if(type==='INDIVIDUAL'&&!normalizePhone(v.phone||v.mobile||'')&&!normalizeEmail(v.email||''))throw new AccessError('INVALID','Téléphone ou email requis.');
  if(type==='INDIVIDUAL'&&!contactSources.includes(v.source))throw new AccessError('INVALID','Source du contact requise.');
  if(v.relationshipStatus&&!relationshipStatuses.includes(v.relationshipStatus))throw new AccessError('INVALID','Statut de relation invalide.');
  if(v.interests&&(!Array.isArray(v.interests)||v.interests.some((i:string)=>!contactInterests.includes(i as typeof contactInterests[number]))))throw new AccessError('INVALID','Intérêt inconnu.');
  if(v.originCenterId&&!await db.prepare('SELECT id FROM service_centers WHERE id=? AND active=1').bind(v.originCenterId).first())throw new AccessError('INVALID','Centre inconnu.');
  if(v.siteId&&!v.accountId)throw new AccessError('INVALID','Un site requiert un compte.');
 }
 if(entity==='opportunities'){
  const type=v.customerType??'B2B';
  if(!['B2B','B2C'].includes(type)||type==='B2B'&&!await exists(db,'accounts',v.accountId))throw new AccessError('INVALID','Compte professionnel requis.');
  if(v.accountId&&!await exists(db,'accounts',v.accountId))throw new AccessError('INVALID','Compte lié introuvable.');
  if(type==='B2C'){
   if(v.accountId||!v.primaryContactId||v.pipelineId!=='services'||v.businessLine!=='Services')throw new AccessError('INVALID','Contact particulier et pipeline Services requis.');
   const contact=await db.prepare('SELECT contact_type AS contactType,account_id AS accountId FROM contacts WHERE id=? AND deleted_at IS NULL').bind(v.primaryContactId).first<{contactType:string;accountId:string|null}>();
   if(contact?.contactType!=='INDIVIDUAL'||contact.accountId)throw new AccessError('INVALID','Contact particulier incompatible.');
  }
  if(v.centerId&&!await db.prepare('SELECT id FROM service_centers WHERE id=? AND active=1').bind(v.centerId).first())throw new AccessError('INVALID','Centre inconnu.');
 }
 if(entity==='contacts'&&v.siteId){const site=await db.prepare('SELECT account_id AS accountId FROM account_sites WHERE id=?').bind(v.siteId).first<{accountId:string}>();if(site?.accountId!==v.accountId)throw new AccessError('INVALID','Site incompatible avec le compte.');}
 if(entity==='opportunities'){
 if(!v.pipelineId||!v.stageId||!Number.isFinite(Number(v.amount))||!['EUR','USD','GBP','AED'].includes(v.currency))throw new AccessError('INVALID','Opportunité incomplète.');
 const stage=await db.prepare('SELECT pipeline_id AS pipelineId FROM pipeline_stages WHERE id=?').bind(v.stageId).first<{pipelineId:string}>();if(stage?.pipelineId!==v.pipelineId)throw new AccessError('INVALID','Étape incompatible avec le pipeline.');
 if(v.status==='Lost'&&!v.lossReason)throw new AccessError('INVALID','Raison de perte requise.');
 if(creating&&v.status==='Open'&&(!v.nextAction?.trim()||!v.nextActionDate))throw new AccessError('INVALID','Prochaine action et date requises.');
 if(v.siteId){const site=await db.prepare('SELECT account_id AS accountId FROM account_sites WHERE id=?').bind(v.siteId).first<{accountId:string}>();if(site?.accountId!==v.accountId)throw new AccessError('INVALID','Site incompatible.');}
 if(v.primaryContactId){const contact=await db.prepare('SELECT account_id AS accountId FROM contacts WHERE id=? AND deleted_at IS NULL').bind(v.primaryContactId).first<{accountId:string|null}>();if(!contact||contact.accountId!==v.accountId)throw new AccessError('INVALID','Contact incompatible.');}
 }
 if(entity==='tasks'&&(!v.dueDate||!['À faire','En cours','Terminée','Annulée'].includes(v.status)))throw new AccessError('INVALID','Tâche incomplète.');
 const hasActivityLink=['prospectId','accountId','contactId','opportunityId'].some(key=>!!v[key]);
 if(entity==='activities'&&v.captureOrigin==='voice'&&!hasActivityLink)throw new AccessError('INVALID','Une note vocale doit être rattachée à un prospect, contact, compte ou opportunité.');
 if(entity==='activities'&&(!v.activityDate||!hasActivityLink))throw new AccessError('INVALID','Date et fiche liée requises pour l’activité.');
 for(const [key,table] of [['prospectId','prospects'],['accountId','accounts'],['contactId','contacts'],['opportunityId','opportunities'],['activityId','activities']] as const){if(v[key]&&!(entity==='prospects'&&key==='opportunityId')&&!(entity==='accounts'&&key==='accountId')&&!(entity==='contacts'&&key==='accountId')&&!(entity==='sites'&&key==='accountId')&&!(entity==='opportunities'&&key==='accountId')&&!(await exists(db,table,String(v[key]))))throw new AccessError('INVALID','Objet lié introuvable.');}
 for(const [key,table,permission] of [['parentId','accounts','account.read'],['accountId','accounts','account.read'],['contactId','contacts','contact.read'],['primaryContactId','contacts','contact.read'],['prospectId','prospects','prospect.read'],['opportunityId','opportunities','opportunity.read']] as const){if(!v[key]||(entity==='prospects'&&key==='opportunityId'))continue;const linked=await db.prepare(`SELECT owner_id AS ownerId FROM ${table} WHERE id=? AND deleted_at IS NULL`).bind(String(v[key])).first<{ownerId:string}>();if(!linked)throw new AccessError('INVALID','Objet lié introuvable.');if(entity==='opportunities'&&key==='accountId'&&previous?.accountId===v.accountId)continue;if((entity==='activities'||entity==='tasks')&&key==='accountId'&&v.opportunityId){const opportunity=await db.prepare('SELECT account_id AS accountId,owner_id AS ownerId FROM opportunities WHERE id=? AND deleted_at IS NULL').bind(String(v.opportunityId)).first<{accountId:string;ownerId:string}>();if(opportunity&&opportunity.accountId===v.accountId&&await allowed(a,'opportunity.read',opportunity.ownerId))continue}await requirePermission(a,permission,linked.ownerId)}
}
export async function candidates(a:Actor,entity:'accounts'|'contacts',v:LegacyPayload){const permission=`${entity==='accounts'?'account':'contact'}.read`;await requirePermission(a,`${entity==='accounts'?'account':'contact'}.create`);let data;if(entity==='accounts')data=await a.db.prepare('SELECT id,payload,owner_id AS ownerId FROM accounts WHERE deleted_at IS NULL AND (normalized_name=? OR (domain!=? AND domain=?) OR (tax_id_normalized!=? AND tax_id_normalized=?) OR (phone_normalized!=? AND phone_normalized=?))').bind(normalizeName(v.name??''),'',normalizeDomain(v.website??''),'',normalizeTaxId(v.taxId??''),'',normalizePhone(v.phone??'')).all<{id:string;payload:string;ownerId:string}>();else{const email=normalizeEmail(v.email??''),phone=normalizePhone(v.phone||v.mobile||''),name=normalizeName(`${v.first??''} ${v.last??''}`);data=await a.db.prepare('SELECT id,payload,owner_id AS ownerId FROM contacts WHERE deleted_at IS NULL AND ((? != ? AND email_normalized=?) OR (? != ? AND phone_normalized=?) OR (? IS NOT NULL AND account_id=? AND name_normalized=?) OR (? != ? AND name_normalized=? AND (phone_normalized LIKE ? OR email_normalized LIKE ?)))').bind(email,'',email,phone,'',phone,v.accountId??null,v.accountId??null,name,name,'',name,phone.length>=7?`%${phone.slice(-7)}`:'__no_match__',email.includes('@')?`${email.split('@')[0]}%`:'__no_match__').all<{id:string;payload:string;ownerId:string}>()}const visible=[];for(const row of data.results)if(await allowed(a,permission,row.ownerId))visible.push(JSON.parse(row.payload));return visible}
const changed=(old:LegacyPayload,value:LegacyPayload)=>Object.keys(value).filter(k=>JSON.stringify(old[k])!==JSON.stringify(value[k]));
export async function save(a:Actor,entity:Entity,value:LegacyPayload,allowDuplicate=false,refreshRate=false){const cfg=entities[entity];if(entity==='activities')value={...value,userId:a.id};const id=idOf(value);const existing=await findRow(a,entity,id);const old=existing?JSON.parse(existing.payload):null;if(entity==='contacts')value={...value,contactType:value.contactType??'BUSINESS',relationshipStatus:value.relationshipStatus??(value.status==='Actif'?'Client actif':value.status==='Inactif'?'Inactif':'Prospect'),interests:value.interests??[]};if(entity==='opportunities')value={...value,customerType:value.customerType??'B2B'};const action=existing?'update':'create';await requirePermission(a,`${cfg.singular}.${action}`,existing?.ownerId??owner(entity,value));
 if(existing&&old.id!==value.id)throw new AccessError('INVALID','Identifiant incohérent.');
 if(existing&&owner(entity,old)!==owner(entity,value)){await requirePermission(a,`${cfg.singular}.assign`,existing.ownerId);await requirePermission(a,`${cfg.singular}.assign`,owner(entity,value))}
 if(entity==='opportunities'){
  if(refreshRate)await requirePermission(a,'admin.rates');
  value={...value,nativeAmount:Number(value.amount)};
  const rateNeedsUpdate=refreshRate||!old||old.amount!==value.amount||old.currency!==value.currency;
  if(value.currency==='EUR')value={...value,exchangeRateSnapshot:1,exchangeRateDate:now().slice(0,10),amountEUR:Number(value.amount)};
  else if(!rateNeedsUpdate&&old)value={...value,exchangeRateSnapshot:old.exchangeRateSnapshot,exchangeRateDate:old.exchangeRateDate,amountEUR:old.amountEUR};
  else if(rateNeedsUpdate){try{const chosen=await rateFor(a,value.currency,now().slice(0,10));value={...value,exchangeRateSnapshot:chosen.rate,exchangeRateDate:chosen.date,amountEUR:Math.round(Number(value.amount)*chosen.rate*100)/100}}catch(e){if(refreshRate)throw e;value={...value,exchangeRateSnapshot:undefined,exchangeRateDate:undefined,amountEUR:undefined}}}
 }
 if(entity==='tasks'&&value.status==='Terminée'&&!value.completedAt)value={...value,completedAt:now()};
 if(entity==='prospects'&&old?.status!=='Converti'&&value.status==='Converti'){await requirePermission(a,'prospect.convert',existing?.ownerId);value={...value,convertedBy:a.id}}
 if(!existing&&['accounts','contacts'].includes(entity)){const duplicates=await candidates(a,entity as 'accounts'|'contacts',value);if(duplicates.length&&!allowDuplicate)throw new AccessError('CONFLICT',`Doublon potentiel : ${duplicates.map(d=>d.name??`${d.first} ${d.last}`).join(', ')}`)}
 await validate(a,entity,value,!existing,old);
 const cols=scalar(entity,value);const statements:ReturnType<DB['prepare']>[]=[];
 if(existing){const keys=Object.keys(cols);statements.push(a.db.prepare(`UPDATE ${cfg.table} SET ${keys.map(k=>`${k}=?`).join(',')} WHERE id=?`).bind(...keys.map(k=>(cols as Record<string,unknown>)[k]),id))}
 else {const insert={id,created_at:now(),...cols};const keys=Object.keys(insert);statements.push(a.db.prepare(`INSERT INTO ${cfg.table} (${keys.join(',')}) VALUES (${keys.map(()=>'?').join(',')})`).bind(...keys.map(k=>(insert as Record<string,unknown>)[k])))}
 const fields=old?changed(old,value):Object.keys(value);const audit=(event:string,oldValue:unknown,newValue:unknown)=>statements.push(a.db.prepare('INSERT INTO audit_logs(id,user_id,timestamp,entity_type,entity_id,action,old_value,new_value) VALUES(?,?,?,?,?,?,?,?)').bind(uuid(),a.id,now(),entity,id,event,oldValue===undefined?null:JSON.stringify(oldValue),newValue===undefined?null:JSON.stringify(newValue)));
 audit(action,old?Object.fromEntries(fields.map(k=>[k,old[k]])):null,Object.fromEntries(fields.map(k=>[k,value[k]])));
 if(!old&&entity==='contacts'&&value.source==='Carte de visite')audit('contact.business_card.create',null,{contextSource:value.contextSource??null});
 if(!old&&entity==='accounts'&&value.source==='Carte de visite')audit('account.business_card.create',null,{});
 if(!old&&entity==='activities'&&value.captureOrigin==='voice')audit('activity.voice.create',null,{extractionProvider:value.extractionProvider??null,prospectId:value.prospectId??null,contactId:value.contactId??null,accountId:value.accountId??null,opportunityId:value.opportunityId??null});
 if(!old&&entity==='tasks'&&value.captureOrigin==='voice')audit('task.voice.create',null,{});
 if(old){if(owner(entity,old)!==owner(entity,value))audit('owner.change',owner(entity,old),owner(entity,value));if(entity==='contacts'&&old.relationshipStatus!==value.relationshipStatus)audit(value.relationshipStatus==='Client actif'?'prospect.to.client':'relationship.status.change',old.relationshipStatus??'Prospect',value.relationshipStatus);if(entity==='opportunities'&&value.voiceValidatedStage&&old.stageId!==value.stageId)audit('stage.voice.validated',old.stageId,value.stageId);if(entity==='opportunities'){for(const key of ['stageId','amount','status'])if(old[key]!==value[key])audit(key==='stageId'?'stage.change':key==='amount'?'amount.change':value.status==='Won'?'mark.won':'mark.lost',old[key],value[key])}if(entity==='prospects'&&value.status==='Converti'&&old.status!=='Converti')audit('prospect.convert',old.status,value.status);if(entity==='tasks'&&old.dueDate!==value.dueDate){statements.push(a.db.prepare('INSERT INTO task_history(id,task_id,user_id,old_date,new_date,timestamp) VALUES(?,?,?,?,?,?)').bind(uuid(),id,a.id,old.dueDate,value.dueDate,now()));audit('task.postpone',old.dueDate,value.dueDate)}}
 await a.db.batch(statements);return value;
}
export async function softDelete(a:Actor,entity:Entity,id:string){const cfg=entities[entity];const old=await findRow(a,entity,id);if(!old)throw new AccessError('INVALID','Objet introuvable.');await requirePermission(a,`${cfg.singular}.delete`,old.ownerId);await a.db.batch([a.db.prepare(`UPDATE ${cfg.table} SET deleted_at=?,deleted_by=? WHERE id=?`).bind(now(),a.id,id),a.db.prepare('INSERT INTO audit_logs(id,user_id,timestamp,entity_type,entity_id,action,old_value,new_value) VALUES(?,?,?,?,?,?,?,?)').bind(uuid(),a.id,now(),entity,id,'delete',old.payload,null)])}
