import {actor,respondError,AccessError,requirePermission} from '@/server/auth';
import {snapshot} from '@/server/repository';
import {normalizeName,normalizeEmail,normalizePhone,normalizeDomain,normalizeTaxId} from '@/server/normalize';
import {createActivity,taskForNextAction} from '@/data/work';
import {rateFor} from '@/server/admin';
import type {Account,Contact,Opportunity,Task} from '@/types/crm';
import type {Prospect} from '@/types/prospect';
export const dynamic='force-dynamic';
export async function POST(request:Request){try{const a=await actor();const {prospect:p,account:acc,contact:c,opportunity:o}=await request.json() as {prospect:Prospect;account:Account|null;contact:Contact|null;opportunity:Opportunity|null};const old=await a.db.prepare('SELECT payload,owner_id AS ownerId FROM prospects WHERE id=? AND deleted_at IS NULL').bind(String(p?.id)).first<{payload:string;ownerId:string}>();if(!old)throw new AccessError('INVALID','Prospect introuvable.');await requirePermission(a,'prospect.convert',old.ownerId);const original=JSON.parse(old.payload) as Prospect;if(original.status==='Converti')throw new AccessError('CONFLICT','Prospect déjà converti.');if(!p.accountId||!p.contactId||p.status!=='Converti'||(!o&&p.opportunityId)||!!o!==!!p.opportunityId)throw new AccessError('INVALID','Compte et contact requis.');
 const db=a.db;const now=new Date().toISOString();const statements:ReturnType<typeof db.prepare>[]=[];const add=(sql:string,...args:unknown[])=>statements.push(db.prepare(sql).bind(...args));
 if(acc){await requirePermission(a,'account.create',acc.ownerId);if(acc.id!==p.accountId)throw new AccessError('INVALID','Compte incohérent.');add('INSERT INTO accounts(id,parent_id,owner_id,name,normalized_name,domain,tax_id_normalized,phone_normalized,payload,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)',acc.id,acc.parentId,acc.ownerId,acc.name,normalizeName(acc.name),normalizeDomain(acc.website),normalizeTaxId((acc as Account & {taxId?:string}).taxId??''),normalizePhone(acc.phone),JSON.stringify(acc),now,now)}else{const exists=await db.prepare('SELECT owner_id AS ownerId FROM accounts WHERE id=? AND deleted_at IS NULL').bind(p.accountId).first<{ownerId:string}>();if(!exists)throw new AccessError('INVALID','Compte introuvable.');await requirePermission(a,'account.read',exists.ownerId)}
 if(c){await requirePermission(a,'contact.create',c.ownerId);if(c.id!==p.contactId||c.accountId!==p.accountId)throw new AccessError('INVALID','Contact incohérent.');add('INSERT INTO contacts(id,account_id,site_id,owner_id,email_normalized,phone_normalized,name_normalized,payload,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)',c.id,c.accountId,c.siteId,c.ownerId,normalizeEmail(c.email),normalizePhone(c.phone),normalizeName(`${c.first} ${c.last}`),JSON.stringify(c),now,now)}else{const existing=await db.prepare('SELECT account_id AS accountId,owner_id AS ownerId FROM contacts WHERE id=? AND deleted_at IS NULL').bind(p.contactId).first<{accountId:string;ownerId:string}>();if(existing?.accountId!==p.accountId)throw new AccessError('INVALID','Contact incompatible avec le compte.');await requirePermission(a,'contact.read',existing.ownerId)}
 if(o){await requirePermission(a,'opportunity.create',o.ownerId);if(o.accountId!==p.accountId||o.id!==p.opportunityId||o.primaryContactId!==p.contactId||!Number.isFinite(Number(o.amount))||!['EUR','USD','GBP','AED'].includes(o.currency))throw new AccessError('INVALID','Opportunité incohérente.');const stage=await db.prepare('SELECT pipeline_id AS pipelineId FROM pipeline_stages WHERE id=?').bind(o.stageId).first<{pipelineId:string}>();if(stage?.pipelineId!==o.pipelineId)throw new AccessError('INVALID','Étape incompatible.');let rate:null|{rate:number;date:string}=null;try{rate=await rateFor(a,o.currency,now.slice(0,10))}catch(e){if(!(e instanceof AccessError)||e.message!=='Taux de change manquant.')throw e}const saved={...o,nativeAmount:Number(o.amount),exchangeRateSnapshot:rate?.rate,exchangeRateDate:rate?.date,amountEUR:rate?Math.round(Number(o.amount)*rate.rate*100)/100:undefined};add('INSERT INTO opportunities(id,account_id,site_id,primary_contact_id,owner_id,pipeline_id,stage_id,status,native_amount,currency,next_action_date,exchange_rate_snapshot,exchange_rate_date,amount_eur,payload,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',o.id,o.accountId,o.siteId,o.primaryContactId,o.ownerId,o.pipelineId,o.stageId,o.status,o.amount,o.currency,o.nextActionDate,rate?.rate??null,rate?.date??null,saved.amountEUR??null,JSON.stringify(saved),now,now)}
 const converted={...original,status:'Converti' as const,accountId:p.accountId,contactId:p.contactId,opportunityId:p.opportunityId??null,convertedAt:now.slice(0,10),convertedBy:a.id};add('UPDATE prospects SET account_id=?,contact_id=?,opportunity_id=?,converted_by=?,payload=?,updated_at=? WHERE id=? AND deleted_at IS NULL',p.accountId,p.contactId,p.opportunityId??null,a.id,JSON.stringify(converted),now,String(p.id));
 const activity=createActivity({type:'Autre',title:'Conversion du prospect',content:`${p.first} ${p.last} converti en compte et contact.`,userId:a.id,activityDate:now.slice(0,10),prospectId:String(p.id),accountId:p.accountId,contactId:p.contactId,opportunityId:p.opportunityId??undefined});add('INSERT INTO activities(id,user_id,prospect_id,account_id,contact_id,opportunity_id,activity_date,payload,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)',activity.id,a.id,String(p.id),p.accountId,p.contactId,p.opportunityId??null,activity.activityDate,JSON.stringify(activity),now,now);
 if(o?.nextActionDate&&o.nextAction){const task:Task=taskForNextAction({accountId:o.accountId??undefined,opportunityId:o.id},o.nextAction,o.nextActionDate,o.ownerId);add('INSERT INTO tasks(id,owner_id,account_id,opportunity_id,due_date,status,payload,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)',task.id,task.ownerId,o.accountId,o.id,task.dueDate,task.status,JSON.stringify(task),now,now)}
 add('INSERT INTO audit_logs(id,user_id,timestamp,entity_type,entity_id,action,old_value,new_value) VALUES(?,?,?,?,?,?,?,?)',crypto.randomUUID(),a.id,now,'prospects',String(p.id),'prospect.convert',old.payload,JSON.stringify(converted));await db.batch(statements);return Response.json(await snapshot(a))}catch(e){return respondError(e)}}
